# Generated by Django 3.1.3 on 2020-11-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plus1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_number', models.TextField(verbose_name='Первое число')),
            ],
        ),
        migrations.CreateModel(
            name='Plus2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_number', models.TextField(verbose_name='Второе число')),
            ],
        ),
    ]
