# Generated by Django 3.1.3 on 2020-11-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20201114_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='division',
            field=models.FloatField(),
        ),
    ]
